[gin]
    [gin.public]
        port  = 8080
        host  = "127.0.0.1"
        debug = true
        [gin.public.noauth]
            routes = [
                "/auth/login",
                "/auth/logout",
            ]
        [gin.public.jwt]
            secret = "secret"
    [gin.admin]
        port  = 8081
        host  = "127.0.0.1"
        debug = true
        [gin.admin.noauth]
            routes = [
                "/auth/login",
                "/auth/logout",
            ]
        [gin.admin.jwt]
            secret = "secret"

[database.config]
    container_name = "gingo-test"
    host          = "localhost"
    port          = "5899"
    database_name = "apidb_test"
    username      = "admin"
    password      = "secret"
